### ISSUE TITLE
Why the runtime is node?

### ISSUE THREAD

**Issue by cagataycali** [eser/serverless-php#1]
Is PHP needs node as dependency anyway?
https://github.com/eserozvataf/serverless-php/blob/90d1c5751829fb983b47cdabbdbfd68bb089d9d6/serverless.yml#L22

**Comment by eser** [comment]
Since AWS Lambda doesn't support PHP as first-citizen on their platform, a bootstrapper layer is needed to execute pre-compiled php binary.

**Comment by cagataycali** [comment]
Oh I gothca! Thanks!
